version: '3.7'

services:
  mongodb_container:
    image: mongo:4.4.8
    container_name: fubuki-ray-asshole-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: user31
      MONGO_INITDB_ROOT_PASSWORD: user31password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - fubuki-asshole

  proxy:
    image: nginx:alpine
    container_name: fubuki-ray-asshole-proxy
    ports:
      - '20238:80'
      - '20234:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./_ssl_certs:/ssl_certs
    restart: 'unless-stopped'
    networks:
      - fubuki-asshole
  server:
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    container_name: fubuki-ray-asshole-server
    ports:
      - '20235:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - fubuki-asshole

networks:
  fubuki-asshole:
    driver: bridge

volumes:
  mongodb_data_container:

  data:
    driver: local
